const motivationalQuotes = [
  "Believe in yourself",
  "Stay positive, work hard, make it happen",
  "Don’t stop until you’re proud",
  "Doubt kills more dreams than failure ever will",
  "The harder you work, the luckier you get",
  "Push yourself, because no one else will",
  "Dream it, wish it, do it",
  "Wake up with determination, go to bed with satisfaction",
  "Great things never come from comfort zones",
  "Success doesn’t come to you, you go to it",
  "Do it now, sometimes later becomes never",
  "Little things make big days",
  "Don’t wait for opportunity, create it",
  "Work hard in silence, let success make the noise",
  "It’s going to be hard, but hard doesn’t mean impossible",
  "Start where you are, use what you have, do what you can",
  "Small progress is still progress",
  "Stay focused and never give up",
  "Discipline is the bridge between goals and success",
  "Hustle until your haters ask if you’re hiring",
  "Focus on progress, not perfection",
  "Consistency beats talent every time",
  "Don’t limit your challenges, challenge your limits",
  "Work while they sleep, learn while they party",
  "Success starts with self-discipline",
  "Winners are not people who never fail, but people who never quit",
  "Difficult roads often lead to beautiful destinations",
  "Stop doubting yourself, work hard, and make it happen",
  "The best view comes after the hardest climb",
  "Stay hungry, stay foolish",
  "Every day is a new beginning",
  "Big dreams have small beginnings",
  "Do something today that your future self will thank you for",
  "The secret of getting ahead is getting started",
  "Opportunities don’t happen, you create them",
  "Your only limit is your mind",
  "Don’t compare yourself to others, compare yourself to the old you",
  "Turn your wounds into wisdom",
  "Don’t be afraid to start over, it’s a chance to build better",
  "One step at a time is still progress",
  "Work smart, work hard, work together",
  "Nothing worth having comes easy",
  "Success is built on daily habits",
  "Don’t fear failure, fear regret",
  "Dream big, start small, act now",
  "Stay consistent, success will follow",
  "Do what you can, with what you have, where you are",
  "Fall seven times and stand up eight",
  "A little progress each day adds up to big results"
];

export default motivationalQuotes;